### PR TITLE
Working

### PR DESCRIPTION
**Pull request by BSGreaves**

### CODE REVIEW

**Comment by BSGreaves** [comment]
@drdreed This one's done, whenever you have a moment. Thx.

**Review by DevDreed — CHANGES_REQUESTED** [review]
Remove notes/comments on css file

**Comment by morecallan** [comment]
@BSGreaves ^^

**Comment by BSGreaves** [comment]
Comments removed, ready again, thx.

**Review by DevDreed — APPROVED** [review]
👍

**Pull request merged**
